#!/bin/bash
#番茄钟脚本#番茄钟脚本#番茄钟脚本

#默认参数
declare -i work_time=25			
declare -i rest_time=5
declare -i s_work_time=25
declare -i s_rest_time=30
declare -i tomato_number=1
declare -i tim=1		#番茄钟计数
declare -i flag=0		#日志时间计数
declare filename
declare -i a_tim=1		#每日番茄钟总计数
filename=`date +%F`

#日志系统：如还未建立当日记录文件则建立
if [ ! -e ~/Documents/log/clock/`date +%F`  ]
then
	touch  /root/Documents/log/clock/`date +%F`
fi
#判断参数
while [ -n "$1" ]
do
	case "$1" in
		-t) tomato_number=$2    #-t 番茄钟个数
			shift;;
		-w) work_time=$2	#-w 工作时间
			s_work_time=$2
			shift;;
		-r) rest_time=$2	#-r 休息时间
			let s_rest_time=work_time+rest_time
			#let rest_time=s_rest_time
			shift;;
		*) echo "$1 is not an option"
			exit 1
	esac
	shift
done

let rest_time=s_rest_time

#判断文件是否为空，并重置当日番茄钟实际个数
if [ -s ~/Documents/log/clock/`date +%F` ]
then
	filelines=`sed -n '$=' /root/Documents/log/clock/$filename`
	let a_tim=filelines/2
	let a_tim=a_tim+1
fi

while [ $tim -le $tomato_number ]
	do
		echo "env DISPLAY=:0 feh -ZF /root/Pictures/$tim.jpg"|at now+$work_time minutes
		echo "Find_PID feh" | at now+$rest_time minutes
		date +%T --date="+$flag minutes" | cut -d ':' -f 1,2>>/root/Documents/log/clock/`date +%F`
		let flag=flag+s_rest_time
		echo "第$a_tim个番茄钟">>/root/Documents/log/clock/`date +%F`
		let work_time=work_time+s_rest_time
		let rest_time=rest_time+s_rest_time
		let tim=tim+1
		let a_tim=a_tim+1
	done
 
unset work_time
unset rest_time
unset s_work_time
unset s_rest_time
unset tomato_number
unset tim

