#! /bin/bash
if [ $# == 0 ]
then
	echo "input name"
	exit 1
else
	NAME=$1
	echo $NAME
	ID=`ps -ef | grep "$NAME" | grep -v "grep" | awk '{print $2}'`
	echo $ID
	echo "---------------"
	for id in $ID
	do
	kill -9 $id
	echo "killed $id"
	done
	echo "---------------"
fi

